export const EscrowStateMachineAbi = [
  {
    inputs: [
      { internalType: "address", name: "initialOwner", type: "address" },
      { internalType: "address", name: "_operator", type: "address" },
      { internalType: "address", name: "_platformFeeWallet", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }], name: "EscrowNotFound", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "uint64", name: "availableAt", type: "uint64" },
    ],
    name: "GracePeriodNotElapsed",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint16[5]", name: "bps", type: "uint16[5]" },
      { internalType: "uint256", name: "sum", type: "uint256" },
    ],
    name: "InvalidPayoutBps",
    type: "error",
  },
  { inputs: [{ internalType: "uint16", name: "bps", type: "uint16" }], name: "InvalidRefundBps", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "enum IEscrowStateMachine.State", name: "current", type: "uint8" },
      { internalType: "enum IEscrowStateMachine.State", name: "required", type: "uint8" },
    ],
    name: "InvalidState",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "enum IEscrowStateMachine.State", name: "current", type: "uint8" },
    ],
    name: "InvalidTransition",
    type: "error",
  },
  { inputs: [{ internalType: "bytes32", name: "orderId", type: "bytes32" }], name: "OrderIdExists", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "orderId", type: "bytes32" }], name: "OrderNotFound", type: "error" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "SafeERC20FailedOperation", type: "error" },
  { inputs: [{ internalType: "address", name: "caller", type: "address" }], name: "UnauthorizedCaller", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: false, internalType: "uint128", name: "frozenAmount", type: "uint128" },
      { indexed: false, internalType: "string", name: "evidenceCid", type: "string" },
    ],
    name: "DisputeInitiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "bytes32", name: "orderId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: false, internalType: "address", name: "seller", type: "address" },
      { indexed: false, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "EscrowCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: false, internalType: "uint128", name: "sellerAmount", type: "uint128" },
      { indexed: false, internalType: "uint128", name: "feeAmount", type: "uint128" },
    ],
    name: "EscrowFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: false, internalType: "uint128", name: "buyerRefund", type: "uint128" },
      { indexed: false, internalType: "uint128", name: "sellerRelease", type: "uint128" },
      { indexed: false, internalType: "uint128", name: "feeAmount", type: "uint128" },
    ],
    name: "ResolutionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "enum IEscrowStateMachine.State", name: "from", type: "uint8" },
      { indexed: true, internalType: "enum IEscrowStateMachine.State", name: "to", type: "uint8" },
      { indexed: false, internalType: "uint128", name: "released", type: "uint128" },
    ],
    name: "StateAdvanced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_GRACE_PERIOD",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_PLATFORM_FEE_BPS",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_GRACE_PERIOD",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "advanceState",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "orderId", type: "bytes32" },
      { internalType: "address", name: "buyer", type: "address" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint128", name: "amount", type: "uint128" },
      { internalType: "uint16[5]", name: "payoutBps", type: "uint16[5]" },
    ],
    name: "createEscrow",
    outputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultGracePeriod",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "disputeResolver",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "escrowCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "uint16", name: "refundBps", type: "uint16" },
    ],
    name: "executeResolution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "finalize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "getEscrow",
    outputs: [
      {
        components: [
          { internalType: "bytes32", name: "orderId", type: "bytes32" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint128", name: "totalAmount", type: "uint128" },
          { internalType: "uint128", name: "releasedAmount", type: "uint128" },
          { internalType: "uint128", name: "frozenAmount", type: "uint128" },
          { internalType: "uint64", name: "deliveredAt", type: "uint64" },
          { internalType: "uint64", name: "gracePeriod", type: "uint64" },
          { internalType: "enum IEscrowStateMachine.State", name: "state", type: "uint8" },
          { internalType: "uint16[5]", name: "payoutBps", type: "uint16[5]" },
        ],
        internalType: "struct IEscrowStateMachine.Escrow",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "orderId", type: "bytes32" }],
    name: "getEscrowByOrderId",
    outputs: [
      {
        components: [
          { internalType: "bytes32", name: "orderId", type: "bytes32" },
          { internalType: "address", name: "buyer", type: "address" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint128", name: "totalAmount", type: "uint128" },
          { internalType: "uint128", name: "releasedAmount", type: "uint128" },
          { internalType: "uint128", name: "frozenAmount", type: "uint128" },
          { internalType: "uint64", name: "deliveredAt", type: "uint64" },
          { internalType: "uint64", name: "gracePeriod", type: "uint64" },
          { internalType: "enum IEscrowStateMachine.State", name: "state", type: "uint8" },
          { internalType: "uint16[5]", name: "payoutBps", type: "uint16[5]" },
        ],
        internalType: "struct IEscrowStateMachine.Escrow",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "orderId", type: "bytes32" }],
    name: "getEscrowIdByOrderId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "string", name: "evidenceCid", type: "string" },
    ],
    name: "initiateDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "operator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeBps",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFeeWallet",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [{ internalType: "uint64", name: "seconds_", type: "uint64" }],
    name: "setDefaultGracePeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "resolver", type: "address" }],
    name: "setDisputeResolver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_operator", type: "address" }],
    name: "setOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint16", name: "bps", type: "uint16" }],
    name: "setPlatformFeeBps",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "wallet", type: "address" }],
    name: "setPlatformFeeWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
] as const;
